package models;
// Generated Jul 14, 2018 3:30:17 PM by Hibernate Tools 4.3.1

/**
 * Vanzari generated by hbm2java
 */
public class Vanzari implements java.io.Serializable {

    private Integer idVanzare;
    private Clienti clienti;
    private Produse produse;
    private int idComanda;
    private int cantitateVanzare;
    private double pretProdus;
    private double totalProdus;

    public Vanzari() {
    }

    public Vanzari(Clienti clienti, Produse produse, int idComanda, int cantitateVanzare, double pretProdus, double totalProdus) {
        this.clienti = clienti;
        this.produse = produse;
        this.idComanda = idComanda;
        this.cantitateVanzare = cantitateVanzare;
        this.pretProdus = pretProdus;
        this.totalProdus = totalProdus;
    }



    
    public Integer getIdVanzare() {
        return this.idVanzare;
    }

    public void setIdVanzare(Integer idVanzare) {
        this.idVanzare = idVanzare;
    }

    public Clienti getClienti() {
        return this.clienti;
    }

    public void setClienti(Clienti clienti) {
        this.clienti = clienti;
    }

    public Produse getProduse() {
        return this.produse;
    }

    public void setProduse(Produse produse) {
        this.produse = produse;
    }

    public int getIdComanda() {
        return this.idComanda;
    }

    public void setIdComanda(int idComanda) {
        this.idComanda = idComanda;
    }

    public int getCantitateVanzare() {
        return this.cantitateVanzare;
    }

    public void setCantitateVanzare(int cantitateVanzare) {
        this.cantitateVanzare = cantitateVanzare;
    }

    public double getPretProdus() {
        return this.pretProdus;
    }

    public void setPretProdus(double pretProdus) {
        this.pretProdus = pretProdus;
    }

    public double getTotalProdus() {
        return this.totalProdus;
    }

    public void setTotalProdus(double totalProdus) {
        this.totalProdus = totalProdus;
    }

}
